/**
 * ───────────────────────────────────────────────────────────────────────────
 *  QR MENU — CLIENT CONFIG
 *  Swap this file (or the values below) for each restaurant / café.
 *
 *  Checklist for a new client:
 *    1. restaurant name, tagline, logo, hero image
 *    2. theme colors
 *    3. phone, WhatsApp (digits only, with country code), address
 *    4. hours & timezone
 *    5. categories + menu items (name, price, photo, description)
 *    6. currency / locale
 * ───────────────────────────────────────────────────────────────────────────
 */

export const CONFIG = {
  restaurant: {
    name: "Musio Café & Kitchen",
    tagline: "Ethiopian · Burgers · Pizza · Fresh Juice",
    eyebrow: "Café  ·  Ethiopian  ·  Kitchen",
    description:
      "A casual Ethiopian café serving classic local dishes, burgers, pizza, pasta, fresh juices, coffee, and desserts.",
    logo: "./assets/logo.svg",
    heroImage:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1600&q=80",
    cuisine: "Ethiopian / International",
  },

  /**
   * Colors become CSS variables at runtime.
   * mode: "light" | "dark"
   */
  theme: {
    mode: "light",
    background: "#F4EFE6",
    surface: "#FFFCF7",
    elevated: "#EDE6D9",
    text: "#1C1612",
    textMuted: "#6B6158",
    primary: "#C45C26",
    primaryContrast: "#FFF8F1",
    accent: "#2F4A3C",
    accentContrast: "#F4EFE6",
    border: "rgba(28, 22, 18, 0.1)",
    overlay: "rgba(20, 14, 10, 0.45)",
    radius: "18px",
    fontDisplay: '"Fraunces", "Times New Roman", serif',
    fontBody: '"Outfit", "Segoe UI", sans-serif',
  },

  locale: "en-ET",
  currency: "ETB",
  priceNote: "Prices in ETB. Tax not included.",

  contact: {
    phone: "+2510000000",
    phoneHref: "+2510000000",
    whatsapp: "2510000000",
    whatsappMessage: "Hi Musio! I’d like to order from the menu.",
    email: "hello@musio09.example",
    address: "142 Grove Street, Portland, OR",
    mapsUrl: "https://maps.google.com/?q=142+Grove+Street+Portland+OR",
    instagram: "whos_mus",
    instagramUrl: "https://instagram.com/whos_mus",
    website: "",
  },

  timezone: "Africa/Addis_Ababa",
  hours: [
    { days: [1, 2, 3, 4, 5], open: "08:00", close: "22:00", label: "Mon–Fri", display: "8:00 am – 10:00 pm" },
    { days: [6, 0], open: "09:00", close: "23:00", label: "Sat–Sun", display: "9:00 am – 11:00 pm" },
  ],

  features: {
    showPhotos: true,
    showFeatured: true,
    showSearch: true,
    showTableField: true,
    allowOrderNotes: true,
    showRating: true,
  },

  rating: {
    score: "4.9",
    label: "Guest favorite",
  },

  order: {
    minOrder: 0,
    pickupLabel: "Order for pickup / table",
    whatsappIntro: "Hello Musio! New order:",
    emptyCartHint: "Add a few plates and send the order on WhatsApp.",
  },

  categories: [
    { id: "breakfast", name: "Breakfast" },
    { id: "ethiopian", name: "Ethiopian Food" },
    { id: "burgers", name: "Burgers & Sandwiches" },
    { id: "pizza", name: "Pizza & Pasta" },
    { id: "sides", name: "Sides" },
    { id: "drinks", name: "Drinks & Juices" },
    { id: "desserts", name: "Desserts" },
  ],

  items: [
    {
      id: "special-ful",
      category: "breakfast",
      name: "Special Ful",
      description: "Warm fava beans topped with egg, tomato, onion, chili, and fresh herbs.",
      price: 180,
      image: "https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
      featured: true,
    },
    {
      id: "chechebsa",
      category: "breakfast",
      name: "Chechebsa",
      description: "Pieces of torn flatbread mixed with spiced butter and honey.",
      price: 220,
      image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=80",
      tags: ["ethiopian", "veg"],
    },
    {
      id: "special-firfir ፍርፍር ",
      category: "breakfast",
      name: "Special Firfir",
      description: "Injera mixed with berbere sauce, butter, onion, and fresh tomato.",
      price: 220,
      image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
      tags: ["ethiopian", "popular"],
    },
    {
      id: "eggs-toast ",
      category: "breakfast",
      name: "Scrambled Eggs & Toast",
      description: "Creamy scrambled eggs with toasted bread, tomato, and fresh salad.",
      price: 180,
      image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
    },

    {
      id: "doro-wot ዶሮ ወጥ",
      category: "ethiopian",
      name: "Doro Wot ዶሮ ወጥ",
      description: "Classic Ethiopian chicken stew with berbere, egg, and injera.",
      price: 480,
      image: "https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=900&q=80",
      tags: ["ethiopian", "popular"],
      featured: true,
    },
    {
      id: "special-tibs",
      category: "ethiopian",
      name: "Special Tibs እስፐሻል ጥብስ",
      description: "Sautéed beef with onion, tomato, peppers, rosemary, and Ethiopian spices.",
      price: 520,
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80",
      tags: ["ethiopian", "popular"],
    },
    {
      id: "special-kitfo ክትፎ",
      category: "ethiopian",
      name: "Special Kitfo  ክትፎ",
      description: "Seasoned minced beef with spiced butter, ayib, and greens.",
      price: 550,
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=900&q=80",
      tags: ["ethiopian"],
    },
    {
      id: "shiro",
      category: "ethiopian",
      name: "Shiro ሽሮ",
      description: "Smooth chickpea stew simmered with berbere and aromatic spices, served with injera.",
      price: 280,
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80",
      tags: ["ethiopian", "veg"],
    },
    {
      id: "beyaynet ",
      category: "ethiopian",
      name: "Beyaynet በያይነት",
      description: "A colorful combination of Ethiopian vegetable and lentil dishes served with injera.",
      price: 350,
      image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
      tags: ["ethiopian", "veg", "popular"],
      featured: true,
    },
    {
      id: "gomen",
      category: "ethiopian",
      name: "Gomen",
      description: "Slow-cooked collard greens with garlic, ginger, and Ethiopian spices.",
      price: 240,
      image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80",
      tags: ["ethiopian", "veg"],
    },

    {
      id: "classic-beef-burger",
      category: "burgers",
      name: "Classic Beef Burger",
      description: "Beef patty, lettuce, tomato, onion, cheese, and house sauce with fries.",
      price: 420,
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
      featured: true,
    },
    {
      id: "crispy-chicken-burger",
      category: "burgers",
      name: "Crispy Chicken Burger",
      description: "Crispy chicken, lettuce, tomato, cheese, and creamy house sauce with fries.",
      price: 390,
      image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
    },
    {
      id: "double-cheeseburger",
      category: "burgers",
      name: "Double Cheeseburger",
      description: "Two beef patties, double cheese, caramelized onion, pickles, and house sauce.",
      price: 520,
      image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
    },
    {
      id: "chicken-sandwich",
      category: "burgers",
      name: "Grilled Chicken Sandwich",
      description: "Grilled chicken, lettuce, tomato, cheese, and garlic mayo in toasted bread.",
      price: 360,
      image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=900&q=80",
      tags: [],
    },

    {
      id: "margherita",
      category: "pizza",
      name: "Margherita Pizza",
      description: "Tomato sauce, mozzarella, basil, and a drizzle of olive oil.",
      price: 420,
      image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=900&q=80",
      tags: ["veg", "popular"],
    },
    {
      id: "chicken-pizza",
      category: "pizza",
      name: "Chicken Pizza",
      description: "Chicken, mozzarella, tomato sauce, onion, green pepper, and herbs.",
      price: 520,
      image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
    },
    {
      id: "beef-special-pizza",
      category: "pizza",
      name: "Beef Special Pizza",
      description: "Seasoned beef, mozzarella, onion, peppers, mushrooms, and house sauce.",
      price: 560,
      image: "https://images.unsplash.com/photo-1566843972142-a7fcb70de55a?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
    },
    {
      id: "musio-special-pizza",
      category: "pizza",
      name: "Musio Special Pizza",
      description: "Beef, chicken, sausage, mushrooms, peppers, onion, and extra mozzarella.",
      price: 650,
      image: "https://images.unsplash.com/photo-1594007654729-407eedc4be65?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
      featured: true,
    },
    {
      id: "creamy-chicken-pasta",
      category: "pizza",
      name: "Creamy Chicken Pasta",
      description: "Pasta tossed with grilled chicken, creamy sauce, mushrooms, and parmesan.",
      price: 450,
      image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
    },

    {
      id: "crispy-fries",
      category: "sides",
      name: "Crispy Fries",
      description: "Golden crispy fries served with house dipping sauce.",
      price: 150,
      image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=80",
      tags: ["veg"],
    },
    {
      id: "beef-sambusa",
      category: "sides",
      name: "Beef Sambusa",
      description: "Crispy pastry filled with seasoned beef, onion, and herbs.",
      price: 120,
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
    },
    {
      id: "garden-salad",
      category: "sides",
      name: "Fresh Garden Salad",
      description: "Lettuce, tomato, cucumber, onion, carrot, and lemon dressing.",
      price: 220,
      image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80",
      tags: ["veg"],
    },

    {
      id: "ethiopian-buna",
      category: "drinks",
      name: "Ethiopian Buna",
      description: "Freshly roasted and brewed Ethiopian coffee, served traditionally.",
      price: 100,
      image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
      featured: true,
    },
    {
      id: "macchiato",
      category: "drinks",
      name: "Macchiato",
      description: "Espresso with steamed milk and a light layer of foam.",
      price: 130,
      image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
    },
    {
      id: "ethiopian-tea",
      category: "drinks",
      name: "Ethiopian Tea",
      description: "Hot black tea with fresh spices and optional milk.",
      price: 80,
      image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=80",
      tags: [],
    },
    {
      id: "mango-juice",
      category: "drinks",
      name: "Fresh Mango Juice",
      description: "Freshly blended mango served chilled.",
      price: 180,
      image: "https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
    },
    {
      id: "avocado-juice",
      category: "drinks",
      name: "Avocado Juice",
      description: "Creamy fresh avocado blended with milk and a touch of honey.",
      price: 200,
      image: "https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
    },
    {
      id: "papaya-juice",
      category: "drinks",
      name: "Fresh Papaya Juice",
      description: "Fresh papaya blended smooth and served chilled.",
      price: 180,
      image: "https://images.unsplash.com/photo-1546549032-9571cd6b27df?auto=format&fit=crop&w=900&q=80",
      tags: [],
    },
    {
      id: "special-spris",
      category: "drinks",
      name: "Special Spris",
      description: "Layered avocado, mango, and papaya juice served in a tall glass.",
      price: 230,
      image: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
      featured: true,
    },
    {
      id: "soft-drink",
      category: "drinks",
      name: "Soft Drink",
      description: "Chilled bottled soft drink.",
      price: 90,
      image: "https://images.unsplash.com/photo-1629203849820-fdd70d49c38e?auto=format&fit=crop&w=900&q=80",
      tags: [],
    },
    {
      id: "bottled-water",
      category: "drinks",
      name: "Bottled Water",
      description: "Chilled bottled drinking water.",
      price: 50,
      image: "https://images.unsplash.com/photo-1564419320461-6870880221ad?auto=format&fit=crop&w=900&q=80",
      tags: [],
    },

    {
      id: "cake-slice",
      category: "desserts",
      name: "Cake Slice",
      description: "Soft house cake served with a light cream topping.",
      price: 180,
      image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
    },
    {
      id: "brownie",
      category: "desserts",
      name: "Chocolate Brownie",
      description: "Rich chocolate brownie with a soft center.",
      price: 160,
      image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=900&q=80",
      tags: ["popular"],
    },
    {
      id: "fruit-salad",
      category: "desserts",
      name: "Fresh Fruit Salad",
      description: "Seasonal fresh fruits served chilled.",
      price: 180,
      image: "https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=900&q=80",
      tags: ["veg"],
    },
  ],
};

/**
 * Optional dark theme — copy these values into `theme` above to switch.
 *
 * theme: {
 *   mode: "dark",
 *   background: "#141210",
 *   surface: "#1C1916",
 *   elevated: "#26211C",
 *   text: "#F4EFE6",
 *   textMuted: "#B4A99C",
 *   primary: "#E08A4F",
 *   primaryContrast: "#1C1612",
 *   accent: "#8FAE96",
 *   accentContrast: "#141210",
 *   border: "rgba(244, 239, 230, 0.12)",
 *   overlay: "rgba(8, 6, 4, 0.6)",
 *   radius: "18px",
 *   fontDisplay: '"Fraunces", "Times New Roman", serif',
 *   fontBody: '"Outfit", "Segoe UI", sans-serif',
 * }
 */
